### ISSUE TITLE
wait for the code~~

### ISSUE THREAD

**Issue by kailigo** [EliSchwartz/DeltaEncoder#1]

**Comment by sheromon** [comment]
I really liked this work. Are there still plans to release code?

**Comment by devraj89** [comment]
@kailigo @sheromon did you guys manage to implement this model ?

**Comment by sheromon** [comment]
@devraj89, I reread the paper, thought about it some more, and decided that it wasn't exactly what I wanted/needed, so no.

**Comment by EliSchwartz** [comment]
Hi guys, 

We are in the process of releasing the code and data, it will take few more weeks due to our organization IP process. Please stay tuned.

**Comment by devraj89** [comment]
Hi @EliSchwartz 
Is it possible to tell us a little bit about the encoder and decoder structure? I tried to code that up in Pytorch but hopelessly failed at it.

Perhaps if you can just share the network architecture? It will be of immense help to use.

Thanks

**Comment by EliSchwartz** [comment]
The encoder and decoder are just 2 dense layers each, nothing too fancy. If you have some specific questions I'd be happy to answer.

**Comment by devraj89** [comment]
Hi @EliSchwartz 
Thanks for your response.

This is what I was trying to do : 
Given X_s, Y_s as the <2048>


Thanks in Advance!

**Comment by EliSchwartz** [comment]
Yes, this is correct.

**Comment by carletes124** [comment]
I cant wait to see the code, the paper is very interesting. Do you know when we will be able to see it? Great job!

**Comment by intersense** [comment]
Interesting work. I want to see the code. Wish a quick release of the code.
