### ISSUE TITLE
Please provide the code 

### ISSUE THREAD

**Issue by devraj89** [EliSchwartz/DeltaEncoder#2]
Hi

Please provide the code for this nice work.
It will be good to at least share the network architecture with the potential users.

I have gone through the paper. can you please confirm the network architecture? based on my understanding when the inputs are `(X_s, Y_s)` which are of `2048 ` dimension. Then the encoder is something like this 

`[2048 dim X | 2048 dim Y]` --> `8192` dim hidden layer --> `16` dim `Z` . `Z` is the encoder output!

I am a bit confused about the decoder architecture. Is it something like this ?
`[Z 16 dim | 2048 dim Y]` --> `8192` dim hidden layer --> `2048` dim.

Any help will be appreciated !

Thanks
Devraj

**Comment by yunlongyu** [comment]
Please provide the code~
Thanks
