### ISSUE TITLE
how to split the dataset?

### ISSUE THREAD

**Issue by lileicv** [EliSchwartz/DeltaEncoder#5]
The validation dataset is not used in the code? Is this reasonable?

**Comment by lileicv** [comment]
为啥子没有人回复我，作者哪里去了？在这里用汉语吐下槽应该没人能看懂吧。

**Comment by zhoumu53** [comment]
看得懂

**Comment by EliSchwartz** [comment]
For the final released model, the training set is composed of both the training and validation sets.

**Comment by lileicv** [comment]
Thank you. @EliSchwartz
